pref("extensions.ankpixiv.showSaveDialog", true);
pref("extensions.ankpixiv.checkExistingDownload", true);
pref("extensions.ankpixiv.saveHistory", true);
pref("extensions.ankpixiv.defaultFilename", '?memoized-name? - ?title?/#page-number#');
pref("extensions.ankpixiv.defaultMangaFilename", '?memoized-name? - ?title? - ?page-number?');
pref("extensions.ankpixiv.largeOnMiddle", true);
pref("extensions.ankpixiv.openComment", false);
pref("extensions.ankpixiv.openCaption", false);
pref("extensions.ankpixiv.alternateFilename", '?memoized-name? - ?title? (?illust-id?)/#page-number#');
pref("extensions.ankpixiv.alternateMangaFilename", '?memoized-name? - ?title? (?illust-id?) - ?page-number?');
pref("extensions.ankpixiv.confirmExistingDownload", true);
pref("extensions.ankpixiv.downloadWhenClickMiddle", false);
pref("extensions.ankpixiv.confirmExistingDownloadWhenAuto", false);
pref("extensions.ankpixiv.showCompletePopup", true);
pref("extensions.ankpixiv.displayDownloaded", true);
pref("extensions.ankpixiv.downloadedDisplayStyle", "color: red; font-weight: bold; font-size: small;");
pref("extensions.ankpixiv.infoText.ignore",  "illust.width, illust.height, illust.year, illust.month, illust.day, illust.hour, illust.minute");
pref("extensions.ankpixiv.saveMeta", true);
pref("extensions.ankpixiv.downloadOriginalSize", false);
pref("extensions.ankpixiv.largeImageSize", 0);
pref("extensions.ankpixiv.dontHidePanel", false);
pref("extensions.ankpixiv.maxPanelOpacity", 100);
pref("extensions.ankpixiv.panelSize", 1);
pref("extensions.ankpixiv.useFacingView", true);
pref("extensions.ankpixiv.useLoadProgress", true);
pref("extensions.ankpixiv.viewOriginalSize", false);
pref("extensions.ankpixiv.useExperimentalModules", false);
pref("extensions.ankpixiv.warnWrongDatetimeFormat", false);
