pref("extensions.ankpixiv.showSaveDialog", true);
pref("extensions.ankpixiv.checkExistingDownload", true);
pref("extensions.ankpixiv.saveHistory", true);
pref("extensions.ankpixiv.defaultFilename", '?member-name? - ?title?');
pref("extensions.ankpixiv.largeOnMiddle", true);
pref("extensions.ankpixiv.openComment", false);
pref("extensions.ankpixiv.alternateFilename", '?member-name? - ?title? (?illust-id?)');
pref("extensions.ankpixiv.confirmExistingDownload", true);
pref("extensions.ankpixiv.downloadWhenClickMiddle", false);
pref("extensions.ankpixiv.confirmExistingDownloadWhenAuto", false);
