@ECHO OFF
REM MODIFY THESE SETTINGS DEPENDING ON YOUR ENVIRONMENT
SET WEB_EXT_SOURCE_DIR=Z:\APT
SET WEB_EXT_FIREFOX_PROFILE=D:\Temp\Firefox\Developer3
SET WEB_EXT_ARTIFACTS_DIR=%WEB_EXT_SOURCE_DIR%\web-ext-artifacts
SET WEB_EXT_NO_RELOAD=true
SET WEB_EXT_KEEP_PROFILE_CHANGES=true
SET WEB_EXT_BROWSER_CONSOLE=true

SET MISC_DIR=%~dp0
SET SRC_DIR=%~dp0\..\source

ECHO # CREATE WORKING DIRECTORY
IF EXIST "%WEB_EXT_SOURCE_DIR%" RD /S/Q "%WEB_EXT_SOURCE_DIR%"
MD "%WEB_EXT_SOURCE_DIR%"
XCOPY /E/Q "%SRC_DIR%\*" "%WEB_EXT_SOURCE_DIR%\"

ECHO # MODIFY manifest.json FOR FIREFOX
python "%MISC_DIR%\add_applications_gecko_id_to_manifest_json.py" -i "%SRC_DIR%" -o "%WEB_EXT_SOURCE_DIR%"

ECHO # EXECUTE FIREFOX IN DEBUG MODE
web-ext run
