"use strict";

const IS_FIREFOX = ((ua)=>{return ua && ua.indexOf("Firefox") != -1})(navigator.userAgent);

const OPTION_DEFAULT ={
  "downloadWhenNice": false,
  //"downloadRate": 10,
  "downloadWhenClickMiddle": false,
  //"initialDirectory": "AnkPixiv",
  "downloadOriginalSize": true,
  //"unpackUgoiraZip": false,
  //"downloadNovelSource": false,
  "saveMeta": true,
  "saveMetaWithPath": true,
  "saveHistory": true,
  "saveHistoryWithDetails": false,
  //"showSaveDialog": false,
  "confirmExistingDownload": true,
  //"confirmExistingDownloadWhenAuto": true,
  "overwriteExistingDownload": false,
  "showIllustRemains": true,
  //"showImageRemains": true,
  //"showCompletePopup": false,
  "hideDownloadShelf": false,
  "cleanDownloadBar": true,
  "displayDownloaded": true,
  "downloadedAnimationStyle": 1,
  "markDownloaded": true,
  //"markUpdated": true,
  "shortTagsMaxLength": 8,
  "forceCheckMangaImagesAll": false,
  "defaultFilename": "AnkPixiv/?site-name?/(?member-id?) ?memoized-name?/?illust-year?-?illust-month?-?illust-day? (?illust-id?) ?title?",
  //"alternateFilename": "AnkPixiv/?site-name?/(?member-id?) ?memoized-name?/?illust-year?-?illust-month?-?illust-day? (?illust-id?) ?title?",
  "mangaImagesSaveToFolder": true,
  //"mangaImagesSaveToZip": false,
  "ignoreWrongDatetimeFormat": false,
  "warnWrongDatetimeFormat": true,
  "largeOnMiddle": true,
  "largeImageSize": 0,
  "dontResizeIfSmall": false,
  "adjustFacingImageHeight": true,
  "maxPanelOpacity": 10,
  "minPanelOpacity": 0,
  "panelSize": 0,
  "loopPage": false,
  "swapArrowButton": false,
  "useFacingView": true,
  "useLoadProgress": true,
  "useImagePrefetch": false,
  "imagePrefetchSize": 5,
  "viewOriginalSize": true,
  //"openComment": false,
  "openCaption": false,
  //"allowThirdPartyCookie": false,
  "xhrFromBackgroundPage": true,
  "logLevel": 3,
  "useExperimentalModule": false,
  //"outputEpubLimit": 4,
  "xhrTimeout": 30000,
  "downloadTimeout": 60000,
  "openCaptionDelay": 1000,
  "historyCacheSize": 200,
  "siteModules": {
    "PXV":{"enabled": true, "experimental": false, "useAutoDownload": true, "useDisplayDownloaded": true, "useMarkDownloaded": true, "useViewer": true, "name": "Pixiv", "folder": "Pixiv"},
    "NJE":{"enabled": true, "experimental": false, "useAutoDownload": true, "useDisplayDownloaded": true, "useMarkDownloaded": true, "useViewer": true, "name": "Nijie", "folder": "Nijie"},
    "NCS":{"enabled": true, "experimental": false, "useAutoDownload": true, "useDisplayDownloaded": true, "useMarkDownloaded": true, "useViewer": true, "name": "Nicosei", "folder": "Nicosei"},
    "TNM":{"enabled": true, "experimental": false, "useAutoDownload": true, "useDisplayDownloaded": true, "useMarkDownloaded": true, "useViewer": true, "name": "Tinami", "folder": "Tinami"},
    "TWT":{"enabled": true, "experimental": false, "name": "Twitter", "folder": "Twitter"},
    "TDK":{"enabled": true, "experimental": false, "name": "Tweetdeck", "folder": "Twitter"}
  }
};

const IMPORT_UNITS = 1000;
const EXPORT_UNITS = 1000;

